my_set1={6,7,9,2,4,0,1,8}
print(my_set1)
#add------
my_set1.add(5)
print(my_set1)
#clear----
my_set1.clear()
print(my_set1)
#copy----
my_set2=my_set1.copy()
my_set2.add(3)
print(my_set2)
print(my_set1)
#differnce---
my_set3={'pranay',2,3,4,'teja','rose'}
diff=my_set3.difference(my_set2)
print(diff)
#differnce_update-----
my_set2.difference_update(my_set3)
print(my_set2)
#discard---
my_set3.discard('rose')
print(my_set3)
#intersection---
inters=my_set1.intersection(my_set2)
print(inters)
#intersection_update----
inters_up=my_set3.intersection_update(my_set2)
print(inters_up)
#isdisjoint----
is_dis=my_set3.isdisjoint(my_set1)
print(is_dis)
#issubset---
is_sub=my_set1.issubset(my_set2)
print(is_sub)
is_sub1=my_set3.issubset(my_set1)
print(is_sub1)
#issuperset----
is_sup=my_set1.issuperset(my_set2)
print(is_sup)
#pop----
my_set1.pop()
print(my_set1)
#remove----
my_set3.remove(4)
print(my_set3)
#symmetric_differnce----
sy_dif=my_set3.symmetric_difference(my_set2)
print(sy_dif)
#symmetric_difference_update---
my_set3.symmetric_difference_update(my_set2)
print(my_set3)
#union----
un=my_set1.union(my_set2)
print(un)
#update----
my_set2.update(my_set3)
print(my_set2)